version: '3.8'

services:
  # ۱. سرویس هوش مصنوعی و API ما
  fraud-api:
    build: .
    container_name: fraud-api
    ports:
      - "8000:8000"
    restart: always

  # ۲. سرویس جمع‌آوری متریک‌ها
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - fraud-api
    restart: always

  # ۳. داشبورد مانیتورینگ
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always
