global:
  scrape_interval: 5s # هر ۵ ثانیه یک‌بار آمار گرفته شود

scrape_configs:
  - job_name: 'fraud-detection-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fraud-api:8000']
